webtalk_init -webtalk_dir /home/elbadri/Multiplier_beta_0.1/Multiplier_beta_0.1/Multiplier_beta.sim/sim_1/behav/xsim.dir/fullSimu_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Mar 10 12:59:50 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1682563" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "206654345_205625595_210619351_146" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1ce44dbc-3e0b-4559-9dc7-4644795e5831" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "18d4734f5bd84371b44306f1a06a3111" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2420 v2 @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2200.109 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "500 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "140500_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2810654998 -regid "206654345_205625595_210619351_146" -xml /home/elbadri/Multiplier_beta_0.1/Multiplier_beta_0.1/Multiplier_beta.sim/sim_1/behav/xsim.dir/fullSimu_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/elbadri/Multiplier_beta_0.1/Multiplier_beta_0.1/Multiplier_beta.sim/sim_1/behav/xsim.dir/fullSimu_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/elbadri/Multiplier_beta_0.1/Multiplier_beta_0.1/Multiplier_beta.sim/sim_1/behav/xsim.dir/fullSimu_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
